@endpoint = {{hostname}}:{{port}}
@hostname = http://localhost
@port = 3001


### GET all persons

GET {{endpoint}}/api/persons HTTP/1.1

### GET a single person

GET {{endpoint}}/api/persons/1 HTTP/1.1

### GET a single person -- Test correct error handling

GET {{endpoint}}/api/persons/0 HTTP/1.1

### Create a new person [POST]

POST {{endpoint}}/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Mario Rossi",
  "number": "333-3333333"
}

### DELETE a person

DELETE {{endpoint}}/api/persons/1 HTTP/1.1

### GET API informations

GET {{endpoint}}/info HTTP/1.1
